import { NextRequest, NextResponse } from "next/server";
import fs from "fs";
import path from "path";
import {
  loadSettings,
  resolveTargetDir,
  targetHasGit,
  runGit,
  GitSettings,
} from "@/lib/git-settings";

/**
 * Default .gitignore written into a freshly initialised environments repo.
 *
 * Excludes derived data (managed-data pulls), per-env credentials (.env files),
 * the local op-history log, and common editor / merge noise. The AIC config
 * tree, env metadata files (log-api.json, release.json, rcs-status.json),
 * and environments.json remain tracked.
 *
 * IGNORE_TOPLEVEL_DIRS / IGNORE_FILE_PATTERNS mirror this list and are used
 * by countDirty() so the "initialize and commit N files" confirmation dialog
 * shows the count that will actually be staged.
 */
const DEFAULT_GITIGNORE = `# PingHub environments — gitignore
#
# Generated by PingHub when this folder was initialised as a git repository.
# Edit freely; PingHub will not overwrite an existing .gitignore.

# Managed-object data pulled by the data-pull pipeline. Each per-type folder
# under <env>/managed-data/<type>/ contains data.ndjson + index.sqlite +
# _manifest.json + _refs.json — all derived, frequently large, and
# re-pullable. .jobs/ holds in-progress / completed pull-job metadata.
managed-data/

# Per-env credentials — never commit secrets.
.env
.env.*

# Operation history log (append-only audit trail, environment-local).
.op-log.jsonl

# Editor / OS noise
.DS_Store
Thumbs.db
*.swp
*~
~$*

# Merge / patch leftovers
*.bak
*.orig
*.rej
`;

const IGNORE_TOPLEVEL_DIRS = new Set([".git", "node_modules", "managed-data"]);
function isIgnoredFileName(name: string): boolean {
  if (name === ".env" || name.startsWith(".env.")) return true;
  if (name === ".op-log.jsonl") return true;
  if (name === ".DS_Store" || name === "Thumbs.db") return true;
  if (name.endsWith(".swp") || name.endsWith("~") || name.startsWith("~$")) return true;
  if (name.endsWith(".bak") || name.endsWith(".orig") || name.endsWith(".rej")) return true;
  return false;
}

/** Write `.gitignore` if absent. Never overwrites a user-managed one. */
function ensureDefaultGitignore(cwd: string): boolean {
  const target = path.join(cwd, ".gitignore");
  if (fs.existsSync(target)) return false;
  fs.writeFileSync(target, DEFAULT_GITIGNORE, "utf8");
  return true;
}

interface PreflightResult {
  reason: "not-initialized" | "branch-mismatch" | "no-commits";
  currentBranch?: string;
  dirtyCount?: number;
  message: string;
}

export async function POST(req: NextRequest) {
  const settings = loadSettings();
  const cwd = resolveTargetDir(settings);
  const body = await req.json().catch(() => ({}));
  const confirmed = body.confirm === true;

  if (!fs.existsSync(cwd)) {
    return NextResponse.json(
      { ok: false, error: `Target dir does not exist: ${cwd}` },
      { status: 400 },
    );
  }
  if (!settings.remoteUrl) {
    return NextResponse.json({ ok: false, error: "Remote URL is required." }, { status: 400 });
  }

  const preflight = detectSetupNeed(cwd, settings);

  if (preflight && !confirmed) {
    return NextResponse.json({
      ok: false,
      needsConfirm: true,
      preflight,
    });
  }

  if (preflight) {
    const applied = applySetup(cwd, settings, preflight);
    if (!applied.ok) {
      return NextResponse.json({ ok: false, error: applied.error, steps: applied.steps }, { status: 500 });
    }
  }

  const pushRes = runGit(["push", "-u", "origin", settings.branch], cwd, 180_000);
  if (!pushRes.ok) {
    const detail = (pushRes.stderr || pushRes.stdout || "").trim();
    return NextResponse.json(
      {
        ok: false,
        error: detail ? `git push failed: ${detail.split("\n")[0]}` : "git push failed",
        stdout: pushRes.stdout,
        stderr: pushRes.stderr,
        steps: [
          {
            cmd: `git push -u origin ${settings.branch}`,
            ok: false,
            out: detail,
          },
        ],
      },
      { status: 500 },
    );
  }
  return NextResponse.json({
    ok: true,
    stdout: pushRes.stdout,
    stderr: pushRes.stderr,
  });
}

function detectSetupNeed(cwd: string, settings: GitSettings): PreflightResult | null {
  if (!targetHasGit(settings)) {
    const dirtyCount = countDirty(cwd, false);
    return {
      reason: "not-initialized",
      dirtyCount,
      message: `"${settings.targetDir}" is not a git repository yet. Initialize it, commit all ${dirtyCount} file(s), and push to origin/${settings.branch}?`,
    };
  }

  const headRes = runGit(["rev-parse", "--verify", "HEAD"], cwd);
  if (!headRes.ok) {
    const dirtyCount = countDirty(cwd, true);
    return {
      reason: "no-commits",
      dirtyCount,
      message: `Branch "${settings.branch}" has no commits yet. Commit ${dirtyCount} file(s) as an initial snapshot and push?`,
    };
  }

  const branchRes = runGit(["rev-parse", "--abbrev-ref", "HEAD"], cwd);
  const currentBranch = branchRes.ok ? branchRes.stdout : "";
  if (currentBranch && currentBranch !== settings.branch) {
    return {
      reason: "branch-mismatch",
      currentBranch,
      message: `Current branch is "${currentBranch}" but settings target "${settings.branch}". Create and switch to "${settings.branch}" before pushing?`,
    };
  }

  return null;
}

interface ApplyResult {
  ok: boolean;
  error?: string;
  steps: { cmd: string; ok: boolean; out: string }[];
}

function applySetup(cwd: string, settings: GitSettings, preflight: PreflightResult): ApplyResult {
  const steps: ApplyResult["steps"] = [];
  const run = (args: string[]) => {
    const res = runGit(args, cwd);
    steps.push({ cmd: `git ${args.join(" ")}`, ok: res.ok, out: res.ok ? res.stdout : res.stderr });
    return res;
  };
  const fail = (label: string) => {
    const last = steps[steps.length - 1];
    const detail = last?.out?.trim();
    return {
      ok: false,
      error: detail ? `${label}: ${detail.split("\n")[0]}` : label,
      steps,
    } as ApplyResult;
  };

  if (preflight.reason === "not-initialized") {
    if (!run(["init", "-b", settings.branch]).ok) return fail("git init failed");
    ensureDefaultGitignore(cwd);
    steps.push({ cmd: "write .gitignore (default)", ok: true, out: "" });
    // Treat exported configs as binary-stable text: never rewrite line endings.
    // Without this, Windows users with global core.autocrlf/safecrlf=true get
    // "git add" exiting non-zero because every JSON pulled from ForgeRock is LF.
    run(["config", "core.autocrlf", "false"]);
    run(["config", "core.safecrlf", "false"]);
    // Allow paths > 260 chars on Windows (long node UUID filenames blow past it).
    run(["config", "core.longpaths", "true"]);
    if (settings.authorName) run(["config", "user.name", settings.authorName]);
    if (settings.authorEmail) run(["config", "user.email", settings.authorEmail]);
    if (!run(["remote", "add", "origin", settings.remoteUrl]).ok)
      return fail("git remote add failed");
  } else {
    // Repo already exists (e.g. "no-commits" path). Seed .gitignore if it is
    // still missing so the initial commit doesn't capture managed-data/secrets.
    if (ensureDefaultGitignore(cwd)) {
      steps.push({ cmd: "write .gitignore (default)", ok: true, out: "" });
    }
    // Idempotent: also pin CRLF settings on existing repos so re-running Push
    // after a manual `git init` still avoids the autocrlf failure.
    run(["config", "core.autocrlf", "false"]);
    run(["config", "core.safecrlf", "false"]);
    run(["config", "core.longpaths", "true"]);
  }

  if (preflight.reason === "branch-mismatch") {
    const created = run(["checkout", "-b", settings.branch]);
    if (!created.ok) {
      const switched = run(["checkout", settings.branch]);
      if (!switched.ok) return fail("git checkout failed");
    }
  }

  const dirty = runGit(["status", "--porcelain"], cwd);
  if (dirty.ok && dirty.stdout.trim()) {
    // Best-effort: if a previous run crashed/timed out, an index.lock may be
    // sitting in .git/. Clean it up before staging so the user doesn't have to
    // manually delete the file. Only safe because spawnSync now uses SIGKILL,
    // so any prior runGit invocation will be reliably dead by the time we get
    // here.
    clearStaleIndexLock(cwd, steps);

    // -c overrides ensure CRLF warnings can never escalate to a failed exit
    // code on Windows, regardless of the user's global git config.
    // 10-min timeout: indexing 10k+ JSON configs on Windows can take several
    // minutes, and any timeout here leaves the process holding index.lock.
    const addRes = runGit(
      [
        "-c",
        "core.autocrlf=false",
        "-c",
        "core.safecrlf=false",
        "-c",
        "core.longpaths=true",
        "add",
        "-A",
      ],
      cwd,
      10 * 60 * 1000,
    );
    steps.push({
      cmd: "git -c core.autocrlf=false -c core.safecrlf=false -c core.longpaths=true add -A",
      ok: addRes.ok,
      out: addRes.ok ? addRes.stdout : addRes.stderr,
    });
    if (!addRes.ok) {
      const stderr = addRes.stderr || "";
      if (/index\.lock.*File exists/i.test(stderr)) {
        return {
          ok: false,
          error:
            "git add failed: another git process is holding .git/index.lock. " +
            "Close any open git command (commit/rebase) on this folder, then retry. " +
            "If nothing is running, delete environments/.git/index.lock manually.",
          steps,
        };
      }
      return fail("git add failed");
    }
    const commitMsg =
      preflight.reason === "not-initialized"
        ? "Initial environments snapshot"
        : "Snapshot before push";
    if (!run(["commit", "-m", commitMsg]).ok) return fail("git commit failed");
  }

  return { ok: true, steps };
}

/**
 * Remove a stale .git/index.lock left over from a crashed or killed git
 * process. We touch the file lazily — only delete it if it's older than 5
 * seconds, to avoid racing a legitimate concurrent git invocation.
 */
function clearStaleIndexLock(cwd: string, steps: ApplyResult["steps"]): void {
  const lock = path.join(cwd, ".git", "index.lock");
  try {
    const stat = fs.statSync(lock);
    const ageMs = Date.now() - stat.mtimeMs;
    if (ageMs < 5_000) return; // probably a real concurrent git, leave it alone
    fs.unlinkSync(lock);
    steps.push({
      cmd: "rm .git/index.lock (stale)",
      ok: true,
      out: `removed lock file (age ${Math.round(ageMs / 1000)}s)`,
    });
  } catch {
    // No lock file, or couldn't stat/unlink — fall through, git will report.
  }
}

function countDirty(cwd: string, requireGit: boolean): number {
  if (requireGit) {
    const res = runGit(["status", "--porcelain"], cwd);
    if (!res.ok) return 0;
    return res.stdout.split("\n").filter((l) => l.trim()).length;
  }
  // Pre-init walk: skip the same patterns our default .gitignore would skip,
  // so the confirmation dialog shows the count that will actually be staged.
  let count = 0;
  const walk = (dir: string) => {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      if (entry.isDirectory()) {
        if (IGNORE_TOPLEVEL_DIRS.has(entry.name)) continue;
        walk(`${dir}/${entry.name}`);
      } else {
        if (isIgnoredFileName(entry.name)) continue;
        count++;
      }
    }
  };
  try {
    walk(cwd);
  } catch {
    /* ignore */
  }
  return count;
}
