import { NextRequest, NextResponse } from "next/server";
import fs from "fs";
import path from "path";
import {
  loadSettings,
  resolveTargetDir,
  targetHasGit,
  runGit,
  GitSettings,
} from "@/lib/git-settings";

/**
 * Default .gitignore written into a freshly initialised environments repo.
 *
 * Excludes derived data (managed-data pulls), per-env credentials (.env files),
 * the local op-history log, and common editor / merge noise. The AIC config
 * tree, env metadata files (log-api.json, release.json, rcs-status.json),
 * and environments.json remain tracked.
 *
 * IGNORE_TOPLEVEL_DIRS / IGNORE_FILE_PATTERNS mirror this list and are used
 * by countDirty() so the "initialize and commit N files" confirmation dialog
 * shows the count that will actually be staged.
 */
const DEFAULT_GITIGNORE = `# PingHub environments — gitignore
#
# Generated by PingHub when this folder was initialised as a git repository.
# Edit freely; PingHub will not overwrite an existing .gitignore.

# Managed-object data pulled by the data-pull pipeline. Each per-type folder
# under <env>/managed-data/<type>/ contains data.ndjson + index.sqlite +
# _manifest.json + _refs.json — all derived, frequently large, and
# re-pullable. .jobs/ holds in-progress / completed pull-job metadata.
managed-data/

# Per-env credentials — never commit secrets.
.env
.env.*

# Operation history log (append-only audit trail, environment-local).
.op-log.jsonl

# Editor / OS noise
.DS_Store
Thumbs.db
*.swp
*~
~$*

# Merge / patch leftovers
*.bak
*.orig
*.rej
`;

const IGNORE_TOPLEVEL_DIRS = new Set([".git", "node_modules", "managed-data"]);
function isIgnoredFileName(name: string): boolean {
  if (name === ".env" || name.startsWith(".env.")) return true;
  if (name === ".op-log.jsonl") return true;
  if (name === ".DS_Store" || name === "Thumbs.db") return true;
  if (name.endsWith(".swp") || name.endsWith("~") || name.startsWith("~$")) return true;
  if (name.endsWith(".bak") || name.endsWith(".orig") || name.endsWith(".rej")) return true;
  return false;
}

/** Write `.gitignore` if absent. Never overwrites a user-managed one. */
function ensureDefaultGitignore(cwd: string): void {
  const target = path.join(cwd, ".gitignore");
  if (fs.existsSync(target)) return;
  fs.writeFileSync(target, DEFAULT_GITIGNORE, "utf8");
}

interface PreflightResult {
  reason: "not-initialized" | "branch-mismatch" | "no-commits";
  currentBranch?: string;
  dirtyCount?: number;
  message: string;
}

export async function POST(req: NextRequest) {
  const settings = loadSettings();
  const cwd = resolveTargetDir(settings);
  const body = await req.json().catch(() => ({}));
  const confirmed = body.confirm === true;

  if (!fs.existsSync(cwd)) {
    return NextResponse.json(
      { ok: false, error: `Target dir does not exist: ${cwd}` },
      { status: 400 },
    );
  }
  if (!settings.remoteUrl) {
    return NextResponse.json({ ok: false, error: "Remote URL is required." }, { status: 400 });
  }

  const preflight = detectSetupNeed(cwd, settings);

  if (preflight && !confirmed) {
    return NextResponse.json({
      ok: false,
      needsConfirm: true,
      preflight,
    });
  }

  if (preflight) {
    const applied = applySetup(cwd, settings, preflight);
    if (!applied.ok) {
      return NextResponse.json({ ok: false, error: applied.error, steps: applied.steps }, { status: 500 });
    }
  }

  const pushRes = runGit(["push", "-u", "origin", settings.branch], cwd, 120_000);
  return NextResponse.json({
    ok: pushRes.ok,
    stdout: pushRes.stdout,
    stderr: pushRes.stderr,
  });
}

function detectSetupNeed(cwd: string, settings: GitSettings): PreflightResult | null {
  if (!targetHasGit(settings)) {
    const dirtyCount = countDirty(cwd, false);
    return {
      reason: "not-initialized",
      dirtyCount,
      message: `"${settings.targetDir}" is not a git repository yet. Initialize it, commit all ${dirtyCount} file(s), and push to origin/${settings.branch}?`,
    };
  }

  const headRes = runGit(["rev-parse", "--verify", "HEAD"], cwd);
  if (!headRes.ok) {
    const dirtyCount = countDirty(cwd, true);
    return {
      reason: "no-commits",
      dirtyCount,
      message: `Branch "${settings.branch}" has no commits yet. Commit ${dirtyCount} file(s) as an initial snapshot and push?`,
    };
  }

  const branchRes = runGit(["rev-parse", "--abbrev-ref", "HEAD"], cwd);
  const currentBranch = branchRes.ok ? branchRes.stdout : "";
  if (currentBranch && currentBranch !== settings.branch) {
    return {
      reason: "branch-mismatch",
      currentBranch,
      message: `Current branch is "${currentBranch}" but settings target "${settings.branch}". Create and switch to "${settings.branch}" before pushing?`,
    };
  }

  return null;
}

interface ApplyResult {
  ok: boolean;
  error?: string;
  steps: { cmd: string; ok: boolean; out: string }[];
}

function applySetup(cwd: string, settings: GitSettings, preflight: PreflightResult): ApplyResult {
  const steps: ApplyResult["steps"] = [];
  const run = (args: string[]) => {
    const res = runGit(args, cwd);
    steps.push({ cmd: `git ${args.join(" ")}`, ok: res.ok, out: res.ok ? res.stdout : res.stderr });
    return res;
  };

  if (preflight.reason === "not-initialized") {
    if (!run(["init", "-b", settings.branch]).ok) return { ok: false, error: "git init failed", steps };
    // Drop in a sensible default .gitignore so the initial commit doesn't
    // capture pulled managed-data, secrets, or the op-log. No-op if the user
    // has already provided one.
    ensureDefaultGitignore(cwd);
    steps.push({ cmd: "write .gitignore (default)", ok: true, out: "" });
    if (settings.authorName) run(["config", "user.name", settings.authorName]);
    if (settings.authorEmail) run(["config", "user.email", settings.authorEmail]);
    if (!run(["remote", "add", "origin", settings.remoteUrl]).ok)
      return { ok: false, error: "git remote add failed", steps };
  }

  if (preflight.reason === "branch-mismatch") {
    const created = run(["checkout", "-b", settings.branch]);
    if (!created.ok) {
      const switched = run(["checkout", settings.branch]);
      if (!switched.ok) return { ok: false, error: created.stderr || "checkout failed", steps };
    }
  }

  const dirty = runGit(["status", "--porcelain"], cwd);
  if (dirty.ok && dirty.stdout.trim()) {
    if (!run(["add", "-A"]).ok) return { ok: false, error: "git add failed", steps };
    const commitMsg =
      preflight.reason === "not-initialized"
        ? "Initial environments snapshot"
        : "Snapshot before push";
    if (!run(["commit", "-m", commitMsg]).ok) return { ok: false, error: "git commit failed", steps };
  }

  return { ok: true, steps };
}

function countDirty(cwd: string, requireGit: boolean): number {
  if (requireGit) {
    const res = runGit(["status", "--porcelain"], cwd);
    if (!res.ok) return 0;
    return res.stdout.split("\n").filter((l) => l.trim()).length;
  }
  // Pre-init walk: skip the same patterns our default .gitignore would skip,
  // so the confirmation dialog shows the count that will actually be staged.
  let count = 0;
  const walk = (dir: string) => {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      if (entry.isDirectory()) {
        if (IGNORE_TOPLEVEL_DIRS.has(entry.name)) continue;
        walk(`${dir}/${entry.name}`);
      } else {
        if (isIgnoredFileName(entry.name)) continue;
        count++;
      }
    }
  };
  try {
    walk(cwd);
  } catch {
    /* ignore */
  }
  return count;
}
